name: 'Terraform CD - Common Infrastructure'
run-name: ${{ inputs.destroy_enabled != true && 'Apply' || 'Destroy' }} ${{ inputs.component }} - ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Select the GitHub Environment to use:'
        required: true
      destroy_enabled:
        required: true
        type: boolean
        description: 'Select to destroy resources, otherwise leave unselected:'
        default: false
      component:
        required: false
        type: choice
        description: 'Select the resource to deploy:'
        options:
          - All

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      review-environment: ${{ steps.get-review-env.outputs.review_env}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Review Environment
        id: get-review-env
        shell: pwsh
        run: |
          if ("${{ inputs.environment }}" -eq "prod") {
            "review_env=ProdReview" >> $env:GITHUB_OUTPUT
          }
          else {
            "review_env=NonProdReview" >> $env:GITHUB_OUTPUT
          }
  TerraformCD:
    needs: [Setup]
    uses: easyjet-dev/reusable-workflows/.github/workflows/terraform-single-approval-cd-using-oidc.yml@v2
    with:
      environment: ${{ inputs.environment }}
      approval_environment: ${{ needs.Setup.outputs.review-environment }}
      tf_version: ${{ vars.TF_VERSION }}
      tf_working_directory: 'terraform/common'
      tf_workspace: '${{ inputs.environment }}'
      tfstate_dynamodb_table: 'tf-locks--commercial-systems'
      tfstate_workspace_key_prefix: '${{ github.event.repository.name }}'
      tfstate_key: 'terraform/common/infrastructure.tfstate'
      destroy_enabled: ${{ inputs.destroy_enabled }}
      tfstate_backend_config_file: '../backends/nonprod.tfbackend'
      additional_tfvars: -var-file=../input-vars/common.tfvars -var-file=../input-vars/${{ inputs.environment }}.tfvars -var=''tag_git_source=${{github.server_url}}/${{github.repository}}'' -var=''tag_git_sha=${{github.sha}}'' -var=''tag_git_branch=${{github.ref_name}}''
    secrets: inherit
